# Generated by Django 6.0 on 2026-01-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_user_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_details',
        ),
    ]
