# Generated by Django 6.0 on 2026-01-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_delete_user_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
